// This file was generated by 'Pattern_Configurator.xlsm'  12:12:10

// Corrected input Pin list for servo platine ver. 1.0 with SMD WS2811
const uint8_t Inp_Prtx[MAX_CHANNEL] = {4, 3, 5 }; // PBx number n
