// This file was generated by 'Pattern_Configurator.xlsm'  15:05:55

// Normal input Pin list for servo platine > Ver 1.0 or DIL WS2811
const uint8_t Inp_Prtx[MAX_CHANNEL] = {3, 4, 5 }; // PBx number n
