/*
 MobaLedLib: LED library for model railways
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 Copyright (C) 2018 - 2021  Hardi Stengelin: MobaLedLib@gmx.de

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
 -------------------------------------------------------------------------------------------------------------
*/

#define CONFIG_ONLY

#include <Arduino.h>

#include "..\LEDs_AutoProg\LEDs_AutoProg.h"   // This file is generated by "Prog_Generator_MobaLedLib.xlsm"


int main()
{
#ifdef USE_EXT_ADDR
  return (int)&Config[0]+(int)&Ext_Addr[0];
#else
  return (int)&Config[0];
#endif
}
/*
//-----------
void setup(){
//-----------
  Serial.begin(115200);
  Serial.print(Config[0]);
}

//-----------
void loop(){
//-----------
}
*/