// This file contains the DCC and LED definitions.
//
// It was automatically generated by the program Prog_Generator_MobaLedLib.xlsm Ver. 0.62      by Hardi
// File creation: 08.12.2019 22:47:12
// (Attention: The display in the Arduino IDE is not updated if Options/External Editor is disabled)

#ifndef __EXT_ADDR_DESC_H__
#define __EXT_ADDR_DESC_H__

#define START_MSG "LEDs_AutoProg Ver 1: extras 08.12.19 22:47"

#define TWO_BUTTONS_PER_ADDRESS 1      // Two buttons (Red/Green) are used (DCC/CAN)
#ifdef NUM_LEDS
  #warning "'NUM_LEDS' definition in the main program is replaced by the included 'LEDs_AutoProg.h' with 32"
  #undef NUM_LEDS
#endif

#define NUM_LEDS 32                    // Number of LEDs (Maximal 256 RGB LEDs could be used)


#define RECEIVE_LED_COLOR_PER_RS232
// Input channel defines for local inputs and expert users



//*******************************************************************
// *** Configuration array which defines the behavior of the LEDs ***
MobaLedLib_Configuration()
  {
  RGB_Heartbeat(0)                                                                                            /* Zeigt an, dass die LEDs angesteuert werden                                                                                                                                                  */  // Reserve LEDs(31)                                                                                         /* // Reserve LEDs(31)                                                                                                                                                                         */
  EndCfg // End of the configuration
  };
//*******************************************************************

//---------------------------------------------
void Set_Start_Values(MobaLedLib_C &MobaLedLib)
//---------------------------------------------
{
}






#endif // __EXT_ADDR_DESC_H__
